// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("AWright18.SimpleExcelExporter")]
[assembly: AssemblyDescriptionAttribute("Extract data into an excel file with ease. ")]
[assembly: AssemblyProductAttribute("AWright18.SimpleExcelExporter")]
[assembly: AssemblyCopyrightAttribute("2017")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-Updating-For-Nuget-Build.1+5.Branch.feature/Updating_For_Nuget_Build.Sha.e6068b379c36cfe323554d72941caa7649bef2a1")]
[assembly: AssemblyMetadataAttribute("githash","")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "AWright18.SimpleExcelExporter";
        internal const System.String AssemblyDescription = "Extract data into an excel file with ease. ";
        internal const System.String AssemblyProduct = "AWright18.SimpleExcelExporter";
        internal const System.String AssemblyCopyright = "2017";
        internal const System.String AssemblyVersion = "0.1.0.0";
        internal const System.String AssemblyFileVersion = "0.1.0.0";
        internal const System.String AssemblyInformationalVersion = "0.1.0-Updating-For-Nuget-Build.1+5.Branch.feature/Updating_For_Nuget_Build.Sha.e6068b379c36cfe323554d72941caa7649bef2a1";
        internal const System.String AssemblyMetadata_githash = "";
    }
}
