// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("SimpleExcelExporter")]
[assembly: AssemblyDescriptionAttribute("Extract data into an excel file with ease. ")]
[assembly: AssemblyProductAttribute("SimpleExcelExporter")]
[assembly: AssemblyCopyrightAttribute("2017")]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
[assembly: AssemblyInformationalVersionAttribute("0.1.0-BuildWithVSTS.1+2.Branch.feature/BuildWithVSTS.Sha.2a26fd884537d5f5dca36c012a89d558cde797a1")]
[assembly: AssemblyMetadataAttribute("githash","")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "SimpleExcelExporter";
        internal const System.String AssemblyDescription = "Extract data into an excel file with ease. ";
        internal const System.String AssemblyProduct = "SimpleExcelExporter";
        internal const System.String AssemblyCopyright = "2017";
        internal const System.String AssemblyVersion = "0.1.0.0";
        internal const System.String AssemblyFileVersion = "0.1.0.0";
        internal const System.String AssemblyInformationalVersion = "0.1.0-BuildWithVSTS.1+2.Branch.feature/BuildWithVSTS.Sha.2a26fd884537d5f5dca36c012a89d558cde797a1";
        internal const System.String AssemblyMetadata_githash = "";
    }
}
